"""Map-independent building enrichment sources (DATA package).

Ingests two public building-footprint sources and normalises them into one
documented form so a later integration step can merge them with OSM.

Sources
-------
* Microsoft GlobalMLBuildingFootprints, release 2026-08-13, CDLA-Permissive-2.0.
  Worldwide per-quadkey GeoJSONL files (gzipped); every height is an ML estimate
  and the dataset marks unknown heights as -1. Index:
  https://bfppub.blob.core.windows.net/$web/2026-08-13/dataset-links.csv
* Overture Maps buildings, pinned release (config), ODbL-1.0. GeoParquet on S3;
  read by bbox via the optional duckdb CLI (isolated subprocess) or from a
  genuine local GeoJSON/GeoJSONSeq file supplied by the user. Overture height is
  treated as *assumed* (mix of OSM tags and modeled estimates), never claimed
  measured.

Normal form (the only shape this module emits)
---------------------------------------------
GeoJSON ``Feature`` with geometry ``Polygon`` or ``MultiPolygon`` in EPSG4326
(lon/lat, WGS84) and exactly these properties::

    source            "microsoft" | "overture"
    source_id         stable id as published (deterministic fallback otherwise)
    release           source release string, e.g. "2026-08-13"
    license           license id, e.g. "CDLA-Permissive-2.0", "ODbL-1.0"
    height            float in metres or None. Finite and positive only;
                      unknown/non-finite/<=0 heights become None.
    height_provenance "ml_estimated" | "overture_assumed", or None when
                      height is None

Features are filtered to proper intersection with the requested bbox (a feature
that crosses, touches, contains or is contained by the bbox is kept; only
disjoint features are dropped), invalid/empty/non-finite geometries and
non-polygon types are dropped, intra-source duplicate ``source_id`` values are
dropped deterministically, and the result is sorted by ``(source, source_id)``.

Caching
-------
Fetch results are cached per ``(source, release, geography)`` where geography is
the requested bbox expanded outward onto a configurable grid (default 0.002°,
~220 m). ``offline=True`` reuses the cache only; a miss is reported as
``offline_cache_miss`` and never silently filled. A failed fetch is never cached
as an empty success: on any download/parse error the affected source reports
status ``error`` and no cache entry is written. Cache entries carry a SHA-256 of
the stored features so reuse is verified.

Public API
----------
    load_candidates(cfg, offline=False, ...) -> (features, audit)
    dedup_osm_priority(features, osm_footprints) -> (kept, dropped_ids)
    dedup_duplicates(features) -> (kept, dropped)
    quadkey_bounds(qk), quadkey_for(lon, lat, z)      # Bing quadkey helpers
    ingest_microsoft / ingest_overture_local / ingest_overture_duckdb

`load_candidates` stays OFF for every map until the map config sets
``building_enrichment.enabled: true`` (integration deliberately explicit).

Anti-magic notes
----------------
* No secret handling anywhere (no credentials are needed; URLs are config-pinned
  and cross-checked against allow-listed hosts/path prefixes).
* duckdb runs as an isolated subprocess with an argument list (never a shell);
  the SQL embeds only software-generated values: a regex-validated release
  string, float-formatted bbox numbers, a config-pinned URL template and a
  cache directory path generated by this module.
* The duckdb query is *bounded, not literally worldless*: it applies row-group
  predicate push-down on the ``bbox`` columns of Overture's partitioned files,
  so the transferred *data rows* are limited to intersecting row groups, but
  duckdb still reads parquet metadata (file/row-group/column stats) of many
  world files and both worlds' network share is internal to duckdb and
  **NOT measured** by this module. Audited byte counts are therefore honest:
  ``downloaded_bytes`` is network bytes this process fetched itself (microsoft
  index+shards, ``None`` when unmeasurable, e.g. the duckdb engine),
  ``extracted_bytes`` is the size of the GeoJSON output actually produced
  (for duckdb: the engine's GeoJSONSeq output), and ``index_bytes``/``shard_bytes``
  split the microsoft download. Timeouts/caps are set via config
  (``duckdb_timeout``, ``file_caps``/``index_caps``, ``SET threads=2``,
  ``PRAGMA memory_limit='2GB'``); they bound the query, they do not bound the
  metadata volume duckdb reads.
"""
from __future__ import annotations

import csv
import gzip
import hashlib
import io
import json
import math
import os
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

import requests
from shapely.geometry import box, mapping, shape
from shapely.prepared import prep

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCES_CONFIG = ROOT / "config" / "building_sources.json"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "buildings"

NORMAL_PROPS = ("source", "source_id", "release", "license", "height", "height_provenance")
SOURCE_PRIORITY = ("overture", "microsoft")  # OSM itself is priority zero at integration
_RELEASE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.\d+$")


class SourceError(Exception):
    """A source could not be fetched/normalised; the failure must be reported,
    not cached as success."""


class FetchError(SourceError):
    pass


# --------------------------------------------------------------------------- #
# Primitive helpers
# --------------------------------------------------------------------------- #

def clean_height(value: Any) -> Optional[float]:
    """Finite, strictly positive height in metres, else None."""
    if value is None:
        return None
    try:
        v = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(v) or v <= 0:
        return None
    return v


def quadkey_bounds(qk: str) -> Tuple[float, float, float, float]:
    """WGS84 bounds ``(west, north, east, south)`` of a Bing quadkey cell."""
    qk = str(qk)
    if not qk or not qk.isdigit():
        raise ValueError(f"not a quadkey: {qk!r}")
    z = len(qk)
    n = 1 << z
    x = y = 0
    for i, ch in enumerate(qk):
        d = int(ch)
        bit = 1 << (z - 1 - i)
        if d & 1:
            x |= bit
        if d & 2:
            y |= bit
    west = x / n * 360.0 - 180.0
    east = (x + 1) / n * 360.0 - 180.0
    north = math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * y / n))))
    south = math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * (y + 1) / n))))
    return (west, north, east, south)


def quadkey_for(lon: float, lat: float, z: int) -> str:
    """Bing quadkey of the tile containing ``(lon, lat)`` at zoom ``z``."""
    n = 1 << z
    x = min(max(int((lon + 180.0) / 360.0 * n), 0), n - 1)
    y = min(max(int((1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n), 0), n - 1)
    out = []
    for i in range(z - 1, -1, -1):
        d = (((y >> i) & 1) << 1) | ((x >> i) & 1)
        out.append(str(d))
    return "".join(out)


def check_bbox(bbox: Sequence[float]) -> Tuple[float, float, float, float]:
    """Validate a ``[west, south, east, north]`` lon/lat bbox."""
    if bbox is None or len(bbox) != 4:
        raise ValueError(f"bbox must be [west, south, east, north], got {bbox!r}")
    w, s, e, n = (float(v) for v in bbox)
    if not all(math.isfinite(v) for v in (w, s, e, n)):
        raise ValueError(f"bbox contains non-finite values: {bbox!r}")
    if not (w < e and s < n):
        raise ValueError(f"bbox must satisfy west<east and south<north: {bbox!r}")
    if not (-180 <= w <= 180 and -180 <= e <= 180 and -90 <= s <= 90 and -90 <= n <= 90):
        raise ValueError(f"bbox outside WGS84: {bbox!r}")
    return (w, s, e, n)


def check_url(url: str, allowed_hosts: Sequence[str], path_prefix: Optional[str] = None,
              suffix: Optional[str] = None) -> str:
    """URL safety gate: https only, host allow-listed, no credentials, no '..',
    optional path-prefix and filename-suffix constraints."""
    p = __import__("urllib.parse", fromlist=["urlparse"]).urlparse(url)
    if p.scheme != "https":
        raise ValueError(f"refusing non-https URL: {url!r}")
    if p.hostname not in allowed_hosts:
        raise ValueError(f"refusing URL on unexpected host {p.hostname!r}")
    if p.username or p.password:
        raise ValueError(f"refusing URL with credentials: {url!r}")
    if ".." in p.path.split("/"):
        raise ValueError(f"refusing URL with dot-dot path: {url!r}")
    if path_prefix and not p.path.startswith(path_prefix):
        raise ValueError(f"URL path {p.path!r} outside allowed prefix {path_prefix!r}")
    if suffix and not p.path.endswith(suffix):
        raise ValueError(f"URL path {p.path!r} does not end with {suffix!r}")
    return url


def fetch_url(url: str, max_bytes: int, max_time: float, chunk: int = 1 << 16) -> bytes:
    """Streamed GET bounded by compressed-byte and wall-clock caps."""
    t0 = time.monotonic()
    try:
        with requests.get(url, stream=True, timeout=(30, max_time)) as resp:
            resp.raise_for_status()
            out = io.BytesIO()
            total = 0
            for part in resp.iter_content(chunk_size=chunk):
                total += len(part)
                if total > max_bytes:
                    raise FetchError(f"download exceeded {max_bytes} bytes cap at {url}")
                if time.monotonic() - t0 > max_time:
                    raise FetchError(f"download exceeded {max_time}s cap at {url}")
                out.write(part)
            return out.getvalue()
    except requests.RequestException as exc:
        raise FetchError(f"GET {url} failed: {exc}") from exc


FetchFn = Callable[[str, int, float], bytes]


# --------------------------------------------------------------------------- #
# Normalisation
# --------------------------------------------------------------------------- #

def _geom_finite(geom: Any) -> bool:
    rings: list = []
    if geom.geom_type == "Polygon":
        rings = [geom.exterior, *geom.interiors]
    elif geom.geom_type == "MultiPolygon":
        for part in geom.geoms:
            rings += [part.exterior, *part.interiors]
    else:
        return False
    for ring in rings:
        for c in ring.coords:
            if not all(math.isfinite(v) for v in c):
                return False
    return True


def _as_lists(obj: Any) -> Any:
    """JSON-stable structure: tuples -> lists (recursing into dicts) so a
    fresh normal form equals the same form after a cache round-trip."""
    if isinstance(obj, dict):
        return {k: _as_lists(v) for k, v in obj.items()}
    if isinstance(obj, (tuple, list)):
        return [_as_lists(x) for x in obj]
    return obj


def normalize_feature(raw: Dict[str, Any], *, source: str, release: str, license_: str,
                      height_provenance: Optional[str], height_field: Optional[str] = "height",
                      id_field: str = "id") -> Optional[Dict[str, Any]]:
    """Convert one raw source feature into the normal form, or None if it is
    invalid (non-polygon, empty, invalid topology, non-finite coordinates)."""
    geom_raw = raw.get("geometry")
    if geom_raw is None:
        return None
    try:
        geom = shape(geom_raw)
    except Exception:
        return None
    if geom.is_empty or not geom.is_valid or geom.geom_type not in ("Polygon", "MultiPolygon"):
        return None
    if not _geom_finite(geom):
        return None
    props = raw.get("properties") or {}
    source_id = str(props.get(id_field) or "").strip()
    if not source_id:  # deterministic fallback id from the geometry itself
        x, y = float(geom.centroid.x), float(geom.centroid.y)
        source_id = f"{source}-auto-{x:.6f}-{y:.6f}-{geom.area:.3f}"
    height = clean_height(props.get(height_field)) if height_field else None
    return {
        "type": "Feature",
        "geometry": _as_lists(mapping(geom)),
        "properties": {
            "source": source,
            "source_id": source_id,
            "release": release,
            "license": license_,
            "height": height,
            "height_provenance": height_provenance if height is not None else None,
        },
    }


def intersects_bbox(geom: Any, bbox: Sequence[float]) -> bool:
    """Proper intersection (keeps crossing/touching/containing features; drops
    only disjoint ones — deliberately NOT a containment-only test)."""
    w, s, e, n = check_bbox(bbox)
    return geom.intersects(box(w, s, e, n))


def _finish(features: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen: set = set()
    out: List[Dict[str, Any]] = []
    for f in features:
        sid = f["properties"]["source_id"]
        if sid in seen:
            continue
        seen.add(sid)
        out.append(f)
    order = {s: i for i, s in enumerate(SOURCE_PRIORITY)}
    out.sort(key=lambda f: (order.get(f["properties"]["source"], len(order)),
                            f["properties"]["source_id"]))
    return out


# --------------------------------------------------------------------------- #
# GeoJSON reading / writing
# --------------------------------------------------------------------------- #

def _write_cache(features: List[Dict[str, Any]], meta: Dict[str, Any],
                 key_dir: Path) -> None:
    key_dir.mkdir(parents=True, exist_ok=True)
    feats_path = key_dir / "features.geojson"
    data = json.dumps({"type": "FeatureCollection", "features": features}, ensure_ascii=False)
    payload = data.encode("utf-8")
    feats_path.write_bytes(payload)
    meta = dict(meta)
    meta["sha256_features"] = hashlib.sha256(payload).hexdigest()
    meta["cached_bytes"] = len(payload)
    meta["features"] = len(features)
    (key_dir / "meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=1), encoding="utf-8")


METRIC_KEYS = ("downloaded_bytes", "extracted_bytes", "index_bytes", "shard_bytes")


def _with_metrics(meta: Dict[str, Any]) -> Dict[str, Any]:
    """Ensure every audit/cache dict carries the metric keys (None = unknown,
    0 = none/not applicable), so CLI consumers can rely on their presence."""
    meta = dict(meta)
    for k in METRIC_KEYS:
        meta.setdefault(k, None)
    return meta


def _options_digest(source_cfg: Dict[str, Any], *, engine: str) -> str:
    """SHA-256 of the config options that change what gets extracted, plus the
    engine, so a cache written under different options/engine is never reused."""
    opts = {k: source_cfg.get(k) for k in (
        "release", "geo_q", "height_provenance", "height_unknown",
        "location_filter", "parquet_s3_template", "local_geojson")}
    opts["engine"] = engine
    raw = json.dumps(opts, sort_keys=True, ensure_ascii=False, default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _read_cache_features(key_dir: Path) -> List[Dict[str, Any]]:
    doc = json.loads((key_dir / "features.geojson").read_text(encoding="utf-8"))
    return list(doc.get("features", []))


def _covers(cached_bbox: Sequence[float], bbox: Sequence[float]) -> bool:
    cw, cs, ce, cn = cached_bbox
    w, s, e, n = bbox
    return cw <= w and cs <= s and ce >= e and cn >= n


def _expand(bbox: Sequence[float], q: float) -> Tuple[float, float, float, float]:
    w, s, e, n = bbox
    return (math.floor(w / q) * q, math.floor(s / q) * q,
            math.ceil(e / q) * q, math.ceil(n / q) * q)


def _geo_key(bbox: Sequence[float], q: float) -> str:
    w, s, e, n = _expand(bbox, q)
    return f"{w:.4f}_{s:.4f}_{e:.4f}_{n:.4f}"


def _source_base(cache_dir: Path, source: str, release: str, bbox: Sequence[float],
                 geo_q: float) -> Tuple[Path, Dict[str, Any]]:
    key_dir = cache_dir / source / release / _geo_key(bbox, geo_q)
    meta = {
        "source": source,
        "release": release,
        "bbox_cached": list(_expand(bbox, geo_q)),
        "bbox_requested": list(bbox),
        "geo_q": geo_q,
    }
    return key_dir, meta


def _try_reuse(key_dir: Path, meta_default: Dict[str, Any], bbox: Sequence[float],
               offline: bool, options_digest: Optional[str] = None) -> Optional[Tuple[List[Dict[str, Any]], Dict[str, Any]]]:
    meta_path, feats_path = key_dir / "meta.json", key_dir / "features.geojson"
    if meta_path.exists() and feats_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            meta = None
        same_opts = meta is not None and (options_digest is None
                                          or meta.get("options_digest") == options_digest)
        if (meta and meta.get("status") == "ok" and same_opts
                and _covers(meta.get("bbox_cached", []), bbox)):
            raw = feats_path.read_bytes()
            if hashlib.sha256(raw).hexdigest() == meta.get("sha256_features"):
                features = _read_cache_features(key_dir)
                add = {"status": "ok", "cached": True, "features": len(features),
                       "warnings": list(meta.get("warnings", [])), "error": None}
                return features, _with_metrics({**meta_default, **meta, **add})
    if offline:
        return [], _with_metrics({"status": "offline_cache_miss", "cached": False,
                                  "error": f"no valid cache at {key_dir} and offline mode refuses network",
                                  "warnings": []})
    return None


# --------------------------------------------------------------------------- #
# Microsoft GlobalMLBuildingFootprints
# --------------------------------------------------------------------------- #

def _parse_index(text: str) -> List[Dict[str, str]]:
    rows = []
    for r in csv.DictReader(io.StringIO(text)):
        rows.append({k.strip().lower(): (v or "").strip() for k, v in r.items()})
    return rows


def select_quadkey_rows(rows: Sequence[Dict[str, str]], bbox: Sequence[float],
                        location: Optional[str] = None) -> List[Dict[str, str]]:
    """Index rows whose quadkey cell intersects the bbox (proper cell overlap,
    not containment). Optional Location filter is a cheap pre-filter."""
    w, s, e, n = check_bbox(bbox)
    out = []
    for r in rows:
        if location and r.get("location") != location:
            continue
        if not r.get("quadkey") or not r.get("url"):
            continue
        try:
            cw, cn, ce, cs = quadkey_bounds(r["quadkey"])
        except ValueError:
            continue
        if cw < e and ce > w and cs < n and cn > s:
            out.append(r)
    out.sort(key=lambda r: r["quadkey"])
    return out


def _iter_geojsonl_gz(data: bytes, t0: float, max_time: float):
    with gzip.GzipFile(fileobj=io.BytesIO(data)) as f:
        for line in f:
            if time.monotonic() - t0 > max_time:
                raise FetchError("decompression exceeded time cap")
            line = line.decode("utf-8", "replace").strip()
            if not line or line[0] == "[":
                continue  # tolerate a wrapped FeatureCollection line
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def fetch_index(source_cfg: Dict[str, Any], cache_root: Path, *, offline: bool,
                fetch: FetchFn = fetch_url) -> bytes:
    """Index CSV for the release, cached next to the per-geography caches so a
    later offline run can resolve quadkey URLs without the network."""
    release = source_cfg["release"]
    idx_dir = cache_root / "microsoft" / release
    idx_file = idx_dir / "index.csv"
    idx_meta = idx_dir / "index.meta.json"
    pinned = source_cfg.get("index_sha256")
    if idx_file.exists() and idx_meta.exists():
        meta = json.loads(idx_meta.read_text(encoding="utf-8"))
        data = idx_file.read_bytes()
        if (meta.get("sha256") == pinned or (not pinned and hashlib.sha256(data).hexdigest() == meta.get("sha256"))):
            return data
    if offline:
        raise SourceError(f"index for release {release} not cached and offline forbids fetching")
    try:
        url = check_url(source_cfg["index_url"], source_cfg["url_hosts"])
    except ValueError as exc:
        raise SourceError(str(exc)) from exc
    caps = source_cfg.get("index_caps", {})
    data = fetch(url, int(caps.get("max_bytes", 64 * 1024 * 1024)), float(caps.get("max_time", 120)))
    if pinned and hashlib.sha256(data).hexdigest() != pinned:
        raise SourceError(f"index SHA-256 mismatch for {release} (pinned {pinned})")
    idx_dir.mkdir(parents=True, exist_ok=True)
    idx_file.write_bytes(data)
    idx_meta.write_text(json.dumps({"sha256": hashlib.sha256(data).hexdigest(),
                                    "bytes": len(data), "url": url},
                                   ensure_ascii=False, indent=1), encoding="utf-8")
    return data


def ingest_microsoft(bbox: Sequence[float], source_cfg: Dict[str, Any], cache_dir: Path,
                     *, offline: bool = False, fetch: FetchFn = fetch_url,
                     t0: Optional[float] = None) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Fetch/normalise Microsoft footprints for a bbox; cache per release+geo."""
    bbox = check_bbox(bbox)
    t0 = t0 if t0 is not None else time.monotonic()
    release = source_cfg["release"]
    geo_q = float(source_cfg.get("geo_q", 0.002))
    digest = _options_digest(source_cfg, engine="microsoft")
    key_dir, meta = _source_base(cache_dir, "microsoft", release, bbox, geo_q)
    reused = _try_reuse(key_dir, meta, bbox, offline, options_digest=digest)
    if reused:
        return reused
    if offline:
        return [], _with_metrics({"status": "offline_cache_miss", "features": 0,
                                  "duration_s": time.monotonic() - t0, "warnings": [],
                                  "error": f"no valid cache for {release} at {key_dir}"})

    index_text = fetch_index(source_cfg, cache_dir, offline=False, fetch=fetch)
    index_bytes = len(index_text)
    rows = select_quadkey_rows(_parse_index(index_text.decode("utf-8-sig")), bbox,
                               location=source_cfg.get("location_filter"))
    if not rows:
        raise SourceError(
            f"microsoft {release}: no index quadkeys intersect bbox {bbox}; "
            "refusing to cache an empty result (cache requires verified coverage)")

    caps = source_cfg.get("file_caps", {})
    max_bytes = int(caps.get("max_bytes", 250 * 1024 * 1024))
    max_time = float(caps.get("max_time", 300))
    host_ok = source_cfg["url_hosts"]
    prefix = source_cfg.get("data_path_prefix")
    features: List[Dict[str, Any]] = []
    seen: set = set()
    shard_bytes = 0
    warnings: List[str] = []
    for r in rows:
        try:
            url = check_url(r["url"], host_ok, path_prefix=prefix, suffix=".csv.gz")
        except ValueError as exc:
            raise SourceError(str(exc)) from exc
        data = fetch(url, max_bytes, max_time)
        shard_bytes += len(data)
        for raw in _iter_geojsonl_gz(data, t0, max_time):
            feat = normalize_feature(raw, source="microsoft", release=release,
                                     license_=source_cfg["license"],
                                     height_provenance=source_cfg.get("height_provenance"))
            if feat is None:
                continue
            if not intersects_bbox(shape(feat["geometry"]), bbox):
                continue
            sid = feat["properties"]["source_id"]
            if sid in seen:
                continue
            seen.add(sid)
            features.append(feat)
    if not features:
        warnings.append(f"microsoft {release}: no matching features in {len(rows)} quadkey file(s)")
    features = _finish(features)
    meta.update(_with_metrics({
        "status": "ok", "license": source_cfg["license"],
        "options_digest": digest, "engine": "microsoft",
        "index_bytes": index_bytes, "shard_bytes": shard_bytes,
        "downloaded_bytes": index_bytes + shard_bytes, "extracted_bytes": 0,
        "duration_s": time.monotonic() - t0,
        "quadkey_files": len(rows), "warnings": warnings, "error": None,
    }))
    _write_cache(features, meta, key_dir)
    return features, _with_metrics({**meta, "cached": False})


# --------------------------------------------------------------------------- #
# Overture Maps buildings
# --------------------------------------------------------------------------- #

def _load_local_bytes(path: Path, max_bytes: int) -> bytes:
    total = 0
    out = io.BytesIO()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(1 << 20)
            if not chunk:
                break
            total += len(chunk)
            if total > max_bytes:
                raise SourceError(f"local file {path} exceeds {max_bytes} bytes cap")
            out.write(chunk)
    return out.getvalue()


def iterate_geojson_bytes(data: bytes):
    """Yield features from a FeatureCollection JSON, a single Feature object,
    or line-delimited GeoJSON (optionally gzipped bytes)."""
    if data[:2] == b"\x1f\x8b":
        data = gzip.decompress(data)
    text = data.decode("utf-8-sig", "replace").lstrip()
    if text.startswith("{"):
        try:
            doc = json.loads(text)
        except json.JSONDecodeError:
            doc = None
        if doc is not None:
            if isinstance(doc, dict) and doc.get("type") == "Feature":
                yield doc
                return
            feats = doc.get("features", []) if isinstance(doc, dict) else []
            for f in feats:
                yield f
            return
    for line in text.splitlines():
        line = line.strip()
        if not line or line[0] == "[":
            continue
        try:
            yield json.loads(line)
        except json.JSONDecodeError:
            continue


def ingest_overture_local(bbox: Sequence[float], source_cfg: Dict[str, Any], cache_dir: Path,
                          local_path: Path, *, offline: bool = False) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Ingest a genuine local Overture extract (GeoJSON/GeoJSONSeq, optional
    .gz). Re-caches when the local input changes (SHA-256 tracked)."""
    bbox = check_bbox(bbox)
    t0 = time.monotonic()
    release = source_cfg["release"]
    geo_q = float(source_cfg.get("geo_q", 0.002))
    if not local_path.is_file():
        raise SourceError(f"local Overture input not found: {local_path}")
    input_sha = hashlib.sha256(_load_local_bytes(local_path, int(source_cfg.get("local_max_bytes", 2 << 30)))).hexdigest()
    digest = _options_digest(source_cfg, engine="local")
    key_dir, meta = _source_base(cache_dir, "overture", release, bbox, geo_q)
    meta_path = key_dir / "meta.json"
    if meta_path.exists():
        try:
            old = json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            old = {}
        if (old.get("status") == "ok" and _covers(old.get("bbox_cached", []), bbox)
                and old.get("input_sha256") == input_sha
                and old.get("options_digest") == digest):
            raw = (key_dir / "features.geojson").read_bytes()
            if hashlib.sha256(raw).hexdigest() == old.get("sha256_features"):
                add = {"status": "ok", "cached": True, "features": len(_read_cache_features(key_dir)),
                       "warnings": [], "error": None}
                return _read_cache_features(key_dir), _with_metrics({**meta, **old, **add})
    if offline:
        return [], _with_metrics({"status": "offline_cache_miss", "features": 0,
                                  "duration_s": time.monotonic() - t0, "warnings": [],
                                  "error": f"no valid cache at {key_dir} and offline forbids reading {local_path}"})
    data = _load_local_bytes(local_path, int(source_cfg.get("local_max_bytes", 2 << 30)))
    features: List[Dict[str, Any]] = []
    seen: set = set()
    warnings: List[str] = []
    for raw in iterate_geojson_bytes(data):
        feat = normalize_feature(raw, source="overture", release=release,
                                 license_=source_cfg["license"],
                                 height_provenance=source_cfg.get("height_provenance"))
        if feat is None:
            continue
        if not intersects_bbox(shape(feat["geometry"]), bbox):
            continue
        sid = feat["properties"]["source_id"]
        if sid in seen:
            continue
        seen.add(sid)
        features.append(feat)
    if not features:
        warnings.append(f"overture {release}: no matching features in {local_path.name}")
    features = _finish(features)
    meta.update(_with_metrics({
        "status": "ok", "license": source_cfg["license"],
        "options_digest": digest, "engine": "local",
        "input_sha256": input_sha, "input_path": str(local_path),
        "downloaded_bytes": 0, "extracted_bytes": len(data),
        "duration_s": time.monotonic() - t0, "warnings": warnings, "error": None,
    }))
    _write_cache(features, meta, key_dir)
    return features, _with_metrics({**meta, "cached": False})


def _duckdb_sql(source_cfg: Dict[str, Any], bbox: Sequence[float], out_path: Path) -> str:
    release = source_cfg["release"]
    if not _RELEASE_RE.match(release):
        raise SourceError(f"refusing non-release release string {release!r}")
    url = (source_cfg.get("parquet_s3_template") or "").format(release=release)
    if not url.startswith("s3://overturemaps-us-west-2/release/") or "{release}" in url:
        raise SourceError(f"parquet URL template not pinned/trusted: {url!r}")
    w, s, e, n = bbox
    out = str(out_path).replace("'", "")
    if not out or "'" in str(out_path):
        raise SourceError("invalid temporary output path for duckdb")
    return (
        "INSTALL httpfs; LOAD httpfs; INSTALL spatial; LOAD spatial;\n"
        "SET s3_region='us-west-2';\n"
        "SET threads=2;\n"
        "PRAGMA memory_limit='2GB';\n"
        "COPY (\n"
        "  SELECT id, height, geometry\n"
        "  FROM read_parquet('" + url + "', hive_partitioning=1)\n"
        "  WHERE bbox.xmin < " + repr(e) + " AND bbox.xmax > " + repr(w) +
        "    AND bbox.ymin < " + repr(n) + " AND bbox.ymax > " + repr(s) + "\n"
        ") TO '" + out + "' (FORMAT GDAL, DRIVER 'GeoJSONSeq');\n"
    )


def ingest_overture_duckdb(bbox: Sequence[float], source_cfg: Dict[str, Any], cache_dir: Path,
                           *, offline: bool = False, duckdb_cli: Optional[str] = None,
                           timeout_s: Optional[float] = None) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Optional bounded Overture query via the duckdb CLI as an isolated
    subprocess (argument list, no shell). Transfers only the parquet row groups
    whose bbox stats intersect the request. Requires a duckdb binary; set
    ``building_enrichment.sources.overture.duckdb: true`` and provide the binary
    via the config (``duckdb_cli``), env ``DUCKDB_CLI`` or PATH."""
    bbox = check_bbox(bbox)
    t0 = time.monotonic()
    release = source_cfg["release"]
    cli = duckdb_cli or os.environ.get("DUCKDB_CLI") or source_cfg.get("duckdb_cli") \
        or shutil.which("duckdb")
    if not cli:
        for cand in (ROOT / ".cache" / "building-deps" / "duckdb-cli",
                     ROOT / ".cache" / "building-deps" / "duckdb" / "duckdb"):
            if cand.is_file():
                cli = str(cand)
                break
    if not cli:
        raise SourceError(
            "overture duckdb requested but no duckdb CLI found (set DUCKDB_CLI or "
            "pass a genuine local Overture GeoJSON via 'local_geojson' instead)")
    geo_q = float(source_cfg.get("geo_q", 0.002))
    digest = _options_digest(source_cfg, engine="duckdb")
    key_dir, meta = _source_base(cache_dir, "overture", release, bbox, geo_q)
    reused = _try_reuse(key_dir, meta, bbox, offline, options_digest=digest)
    if reused:
        return reused
    if offline:
        return [], _with_metrics({"status": "offline_cache_miss", "features": 0,
                                  "duration_s": time.monotonic() - t0, "warnings": [],
                                  "error": f"no valid cache for {release} at {key_dir}"})
    tmp = cache_dir / "overture" / release / "tmp"
    tmp.mkdir(parents=True, exist_ok=True)
    out_path = tmp / f"bbox_{_geo_key(bbox, geo_q)}.geojsonseq"
    sql = _duckdb_sql(source_cfg, bbox, out_path)
    try:
        proc = subprocess.run([cli, "-c", sql], capture_output=True, text=True,
                              timeout=timeout_s or float(source_cfg.get("duckdb_timeout", 600)))
    except FileNotFoundError as exc:
        raise SourceError(f"duckdb CLI not runnable: {cli}") from exc
    except subprocess.TimeoutExpired as exc:
        raise SourceError(f"duckdb query timed out after {timeout_s or 600}s") from exc
    if proc.returncode != 0 or not out_path.exists():
        tail = (proc.stderr or proc.stdout or "")[-1000:]
        raise SourceError(f"duckdb query failed (rc={proc.returncode}): {tail}")
    data = out_path.read_bytes()
    features = []
    for raw in iterate_geojson_bytes(data):
        feat = normalize_feature(raw, source="overture", release=release,
                                 license_=source_cfg["license"],
                                 height_provenance=source_cfg.get("height_provenance"))
        if feat is None:
            continue
        if not intersects_bbox(shape(feat["geometry"]), bbox):
            continue
        features.append(feat)
    out_path.unlink(missing_ok=True)
    features = _finish(features)
    # Network bytes the duckdb CLI transferred are NOT measured by this process
    # (duckdb does its own HTTP) and must never be inferred from output size;
    # report only what we know: the extracted GeoJSON output bytes.
    meta.update(_with_metrics({
        "status": "ok", "license": source_cfg["license"],
        "options_digest": digest, "engine": "duckdb",
        "downloaded_bytes": None, "extracted_bytes": len(data),
        "duration_s": time.monotonic() - t0, "warnings": [], "error": None,
    }))
    _write_cache(features, meta, key_dir)
    return features, _with_metrics({**meta, "cached": False})


# --------------------------------------------------------------------------- #
# Dedup helpers (called by integration; not applied inside load_candidates)
# --------------------------------------------------------------------------- #

def dedup_osm_priority(features: Sequence[Dict[str, Any]],
                       osm_footprints: Sequence[Any]) -> Tuple[List[Dict[str, Any]], List[str]]:
    """OSM stays authoritative: drop every candidate feature whose polygon
    intersects any OSM footprint. Returns ``(kept, dropped_source_ids)``."""
    prepped = [prep(fp) for fp in osm_footprints
               if fp is not None and not fp.is_empty and fp.is_valid
               and fp.geom_type in ("Polygon", "MultiPolygon")]
    kept: List[Dict[str, Any]] = []
    dropped: List[str] = []
    for f in features:
        if any(p.intersects(shape(f["geometry"])) for p in prepped):
            dropped.append(f["properties"]["source_id"])
        else:
            kept.append(f)
    return kept, dropped


def dedup_duplicates(features: Sequence[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Deterministic dedup across ingested sources: the same ``source_id``
    anywhere collapses to the higher-priority source, and exactly matching
    footprints (coordinates equal to 1e-6) collapse the same way. Returns
    ``(kept, dropped_source_ids)``."""
    import shapely.wkt
    order = {src: i for i, src in enumerate(SOURCE_PRIORITY)}
    first_id: Dict[str, Dict[str, Any]] = {}
    geo_owner: Dict[str, str] = {}
    kept: List[Dict[str, Any]] = []
    dropped: List[str] = []
    for f in sorted(features, key=lambda f: (order.get(f["properties"]["source"], 9), f["properties"]["source_id"])):
        p = f["properties"]
        geom = shape(f["geometry"])
        gkey = shapely.wkt.dumps(geom, rounding_precision=6)
        if p["source_id"] in first_id or gkey in geo_owner:
            dropped.append(p["source_id"])
            continue
        first_id[p["source_id"]] = f
        geo_owner[gkey] = p["source_id"]
        kept.append(f)
    return kept, dropped


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #

def _resolve(path: Optional[str], default: Path, base: Optional[Path] = None) -> Path:
    if not path:
        return default
    p = Path(path).expanduser()
    return p if p.is_absolute() else (base or ROOT) / p


def load_candidates(cfg: Dict[str, Any], *, offline: bool = False,
                    cache_dir: Optional[Path] = None,
                    sources_config: Optional[Any] = None,
                    fetch: FetchFn = fetch_url,
                    duckdb_cli: Optional[str] = None,
                    base: Optional[Path] = None) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Return ``(features, audit)`` for one map config dict.

    Relative paths resolve against ``base`` (the build's config root); only legacy
    callers without it fall back to the repository checkout.

    ``cfg`` is a map config (as in ``config/<id>.json``) with a bbox
    ``[west, south, east, north]``; enrichment runs only when
    ``cfg["building_enrichment"]["enabled"]`` is true (explicit opt-in, default
    off). ``building_enrichment`` keys:

        enabled          bool (required for any ingestion)
        sources_config   path or dict (default config/building_sources.json)
        cache_dir        path (default .cache/buildings)
        sources          dict of {name: override} or list of names to limit
        sources.overture.local_geojson   genuine local Overture GeoJSON input
        sources.overture.duckdb          true to attempt the duckdb CLI query

    The returned audit dict (JSON-serialisable) is:

        status     ok | partial | error | disabled | offline_cache_miss | no_source_data
        map_id, bbox_requested, features,
        sources {name: {status, release, license, features, cached,
                        downloaded_bytes, duration_s, warnings, error}}

    On any source error no cache entry is written for that source; statuses lets
    integration refuse to proceed when data is missing rather than empty.
    """
    raw_bbox = cfg.get("bbox")
    if raw_bbox is None:
        raise ValueError("cfg['bbox'] [west,south,east,north] is required for enrichment")
    audit: Dict[str, Any] = {
        "map_id": str(cfg.get("id", "?")),
        "bbox_requested": list(raw_bbox),
        "features": 0,
        "sources": {},
        "warnings": [],
    }
    bbox = check_bbox(list(raw_bbox))
    en = cfg.get("building_enrichment")
    if not isinstance(en, dict) or not en.get("enabled"):
        audit["status"] = "disabled"
        return [], audit

    sc = sources_config or en.get("sources_config") or DEFAULT_SOURCES_CONFIG
    if isinstance(sc, (str, Path)):
        source_config = json.loads(_resolve(str(sc), DEFAULT_SOURCES_CONFIG, base).read_text(encoding="utf-8"))
    elif isinstance(sc, dict):
        source_config = sc
    else:
        raise ValueError(f"bad sources_config: {sc!r}")

    cache_root = cache_dir if cache_dir is not None else _resolve(en.get("cache_dir"), DEFAULT_CACHE_DIR, base)

    active = en.get("sources")
    if isinstance(active, (list, tuple, set)):
        active = {name: {} for name in active}
    active = active or {}

    features: List[Dict[str, Any]] = []
    statuses = set()
    for name in SOURCE_PRIORITY:
        if active and name not in active:
            continue
        base_cfg = source_config.get("sources", {}).get(name) or {}
        override = active.get(name) or {}
        src_cfg = {**base_cfg, **{k: v for k, v in override.items() if v is not None}}
        try:
            src_audit: Dict[str, Any]
            if name == "microsoft":
                feats, src_audit = ingest_microsoft(bbox, src_cfg, cache_root,
                                                    offline=offline, fetch=fetch)
            else:  # overture
                local = src_cfg.get("local_geojson")
                if local:
                    feats, src_audit = ingest_overture_local(
                        bbox, src_cfg, cache_root, _resolve(str(local), (base or ROOT) / "none.geojson", base),
                        offline=offline)
                elif src_cfg.get("duckdb"):
                    feats, src_audit = ingest_overture_duckdb(bbox, src_cfg, cache_root,
                                                              offline=offline, duckdb_cli=duckdb_cli)
                else:
                    feats, src_audit = [], _with_metrics({
                        "status": "no_input", "release": src_cfg.get("release"),
                        "license": src_cfg.get("license"), "features": 0,
                        "downloaded_bytes": 0, "extracted_bytes": 0, "duration_s": 0.0,
                        "warnings": ["no local_geojson and duckdb not enabled; "
                                     "nothing genuine to ingest"], "error": None,
                    })
            features.extend(feats)
            statuses.add(src_audit.get("status", "error"))
            audit["sources"][name] = src_audit
        except SourceError as exc:
            statuses.add("error")
            audit["sources"][name] = _with_metrics({
                "status": "error", "release": src_cfg.get("release"),
                "license": src_cfg.get("license"), "features": 0, "downloaded_bytes": 0,
                "extracted_bytes": 0, "duration_s": 0.0, "warnings": [], "error": str(exc),
            })

    features = _finish(features)
    audit["features"] = len(features)
    if "error" in statuses:
        overall = "error" if statuses == {"error"} else "partial"
    elif "offline_cache_miss" in statuses:
        overall = "offline_cache_miss"
    elif not statuses or statuses == {"no_input"}:
        overall = "no_source_data"
    else:
        overall = "ok"
    audit["status"] = overall
    audit["warnings"] = [f'{k}: {v.get("warnings", [])}' for k, v in audit["sources"].items() if v.get("warnings")]
    return features, audit